import { contacts } from "@/utils/constant";
import {
  Coffee,
  ElectronicSafe,
  MiniBar,
  PlungePool,
  Spa,
  Television,
} from "@/utils/roomAmenitiesIcon";
export const roomsPageData = {
  bannerData: {
    title: "Rooms & Cottages",
  },

  rooms: [
    {
      images: [
        "/superior/IMG_8024.webp",
        "/superior/IMG_8027.webp",
        "/superior/IMG_8028.webp",
        "/superior/IMG_8089.webp",
        "/superior/IMG_8090.webp",
        "/superior/IMG_8093.webp",
        "/superior/IMG_8094.webp",
        "/superior/IMG_8095.webp",
        "/superior/IMG_8097.webp",
        "/superior/IMG_8100.webp",
      ],
      name: "Superior Rooms",
      details: ["2 Pax", "1 King Bed"],
      size: "480 sq. ft.",
      rating: "4.9",
      description:
        "Our Superior Rooms offer a refined blend of contemporary comfort and natural serenity, featuring spacious interiors with private balconies that overlook lush garden landscapes. Thoughtfully designed for relaxation and functionality, these 390 sq. ft. rooms provide a calm retreat—ideal for unwinding after a day of exploration or enjoying quiet moments immersed in nature’s tranquility.",
      amenities: [
        { name: "Tea/Coffee Maker", icon: <Coffee /> },
        { name: "Plunge Pool", icon: <PlungePool /> },
        { name: "Spa", icon: <Spa /> },
        { name: "Television", icon: <Television /> },
        { name: "Mini Bar", icon: <MiniBar /> },
        { name: "Electronic Safe", icon: <ElectronicSafe /> },
      ],
      cta: { label: "Book Now", href: contacts.WhatsAppCta },
    },
    {
      images: [
        "/classic/IMG_8043.webp",
        "/classic/IMG_8046.webp",
        "/classic/IMG_8050.webp",

        "/classic/IMG_8061.webp",
        "/classic/IMG_8069.webp",
        "/classic/IMG_8072.webp",
        "/classic/IMG_8077.webp",
        "/classic/IMG_8130.webp",
        "/classic/IMG_8134.webp",
        "/classic/IMG_8137.webp",
        "/classic/IMG_8079.webp",
        "/classic/IMG_8057.webp",
        "/classic/IMG_8058.webp",
        "/classic/IMG_8083.webp",
        "/classic/IMG_8085.webp",
        "/classic/IMG_8032.webp",
      ],
      name: "Classic Cottages",
      size: "480 sq. ft.",
      rating: "4.9",
      details: ["2 Pax", "1 King Bed"],
      description:
        "Our Classic Cottages offer a seamless blend of plush interiors and private open sit-outs overlooking serene garden views, creating an elegant indoor–outdoor experience. Thoughtfully designed for complete privacy, these cottages are nestled amid rustic surroundings and lush greenery—perfect for unwinding after a jungle safari or enjoying a romantic candlelight evening curated by our butlers",
      amenities: [
        { name: "Tea/Coffee Maker", icon: <Coffee /> },
        { name: "Plunge Pool", icon: <PlungePool /> },
        { name: "Spa", icon: <Spa /> },
        { name: "Television", icon: <Television /> },
        { name: "Mini Bar", icon: <MiniBar /> },
        { name: "Electronic Safe", icon: <ElectronicSafe /> },
      ],
      cta: { label: "Book Now", href: contacts.WhatsAppCta },
    },
    {
      images: [
        "/premium-cottages/IMG_8114.webp",
        "/premium-cottages/IMG_8109.webp",
        "/premium-cottages/IMG_8118.webp",
        "/premium-cottages/IMG_8120.webp",
        "/premium-cottages/IMG_8124.webp",
        "/premium-cottages/IMG_8142.webp",
      ],
      name: "Premium Cottages",
      size: "480 sq. ft.",
      rating: "4.9",
      details: ["2 Pax", "1 King Bed"],
      description:
        "Our Premium Cottages elevate the stay experience with expansive interiors and uninterrupted pool-facing views, creating a vibrant yet indulgent ambiance. Designed with sophisticated furnishings and refined detailing, these spacious retreats are ideal for guests seeking upscale comfort—whether lounging by the pool or enjoying relaxed evenings in a stylish, resort-inspired setting.",
      amenities: [
        { name: "Tea/Coffee Maker", icon: <Coffee /> },
        { name: "Plunge Pool", icon: <PlungePool /> },
        { name: "Spa", icon: <Spa /> },
        { name: "Television", icon: <Television /> },
        { name: "Mini Bar", icon: <MiniBar /> },
        { name: "Electronic Safe", icon: <ElectronicSafe /> },
      ],
      cta: { label: "Book Now", href: contacts.WhatsAppCta },
    },
    {
      images: [
        "/Plunge/IMG_8069.webp",
        "/Plunge/IMG_8077.webp",
        "/Plunge/IMG_8043.webp",
        "/Plunge/IMG_8090.webp",
        "/Plunge/IMG_8094.webp",
        "/Plunge/IMG_8134.webp",
        "/Plunge/IMG_8142.webp",
        "/Plunge/IMG_8190.webp",
        "/Plunge/IMG_8193.webp",
        "/Plunge/IMG_8194.webp",
        "/Plunge/IMG_8204.webp",
        "/Plunge/IMG_8205.webp",
        "/Plunge/IMG_8058.webp",
        "/Plunge/IMG_8187.webp",
      ],
      name: "Plunge Pool Cottages",
      size: "700 sq. ft.",
      details: ["2 Pax", "1 King Bed"],
      rating: "4.9",
      description:
        "Our Plunge Pool Cottages redefine luxury and seclusion, offering standalone accommodations with a private plunge pool and exclusive sun deck. Designed for intimate escapes, these 470 sq. ft. cottages combine spacious, high-end interiors with complete privacy—perfect for honeymooners and couples seeking a serene, personalized retreat immersed in nature.",
      amenities: [
        { name: "Tea/Coffee Maker", icon: <Coffee /> },
        { name: "Plunge Pool", icon: <PlungePool /> },
        { name: "Spa", icon: <Spa /> },
        { name: "Television", icon: <Television /> },
        { name: "Mini Bar", icon: <MiniBar /> },
        { name: "Electronic Safe", icon: <ElectronicSafe /> },
      ],
      cta: { label: "Book Now", href: contacts.WhatsAppCta },
    },
  ],
};
