import type { Metadata } from "next";
import { Aboreto, Montserrat } from "next/font/google";
import "./globals.css";
import "./styles.scss";



const aboreto = Aboreto({
  variable: "--font-aboreto",
  weight: "400",
  subsets: ["latin"],
});


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${aboreto.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body >{children}</body>
    </html>
  );
}
